
name: Build-Package Chef Cookbooks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install chef
      uses: actionshub/chef-install@main
        
    - name: Install cookbooks
      run: berks vendor
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        run: echo "Tests"
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: <tofill>
        release_name: <tofill>
        draft: true
        prerelease: false
    