
name: Build-Package Chef Cookbooks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install chef
      uses: actionshub/chef-install@main
        
    - name: Install cookbooks
      run: berks vendor